version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 913524908137.dkr.ecr.us-east-1.amazonaws.com
      - echo Pulling base image from ECR...
      - docker pull --platform linux/amd64 913524908137.dkr.ecr.us-east-1.amazonaws.com/base-images/node:18-alpine
  build:
    commands:
      - echo Building frontend Docker image...
      - docker build --platform linux/amd64 --build-arg REACT_APP_BACKEND_URL=http://KnightFam-2043196611.us-east-1.amazonaws.com -t frontend-image frontend/
      - echo Tagging the image...
      - docker tag frontend-image:latest 913524908137.dkr.ecr.us-east-1.amazonaws.com/frontend-image:latest
  post_build:
    commands:
      - echo Pushing frontend image to ECR...
      - docker push 913524908137.dkr.ecr.us-east-1.amazonaws.com/frontend-image:latest
